<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>趣邮明信片</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <link rel="stylesheet" href="/css/reset.css?<?php echo $tag; ?>"/>
    <link rel="stylesheet" href="/css/addressbook.css?<?php echo $tag; ?>"/>
</head>
<body>
<input type="hidden" id="var-user-name" value="<?php echo $userName; ?>" />
<div class="container">

    <div id="sharetips" class="popbox pa hide" style="padding-top:0">
        <img src="../images/share_tips.png" style="width: 100%; height: 100%" />
    </div>
    <div class="popbox pa hide">
        <div class="pop-wrapper hint">
            <h2 class="pop-title"></h2>
            <p class="pop-message"></p>
            <button class="pop-close-button">关闭</button>
        </div>
    </div>
    <!--弹出窗-->
    <div id="pop-address" class="pop2 pop2-ab pa hide">
        <div class="bgK pa"><img src="/images/edit_contact_bg.png?<?php echo $tag; ?>" alt=""/></div>
        <div class="edit_title pa">编辑收信人地址</div>
        <input class="recipient_input pa" type="text" placeholder="收件人姓名"/>
        <input class="province_input pa" type="text" placeholder="省"/>
        <input class="city_input pa" type="text" placeholder="市"/>
        <input class="district_input pa" type="text" placeholder="区"/>
        <input class="address_input pa" type="text" placeholder="街道地址、门牌号"></input>
        <input class="postcode_input pa" type="text" placeholder="邮政编码"/>
        <input class="mobile_input pa" type="text" placeholder="联系电话"/>
        <div class='menu-btn-hc menu-btn-pop pa'>
            <input id="pop-cancel" type="image" src="/images/back_btn.png?<?php echo $tag; ?>" alt="取消"/>
            <input id="pop-confirm" type="image" src="/images/save_btn.png?<?php echo $tag; ?>" alt="确定"/>
        </div>
    </div>

    <!-- 地址簿 template -->
    <div id="address-template" style="display:none">
        <div class="list-info-ab">
            <p class="addr-title"></p>
            <ul>
                <li><i>姓名：</i><span class='name-hc addr-name'></span></li>
                <li>
                    <i>地址：</i>
                    <span class='addr-hc addr-addr'>test</span>
                </li>
                <li><i>邮编：</i><span class='post-hc addr-post'></span></li>
                <button class='sel-btn-hc delete_hc'></button>
                <button class='sel-btn-hc edit_hc'></button>
            </ul>
        </div>
    </div>

    <!-- 地址簿 -->
    <div class='list-wrap-hc pa' id='list'  style="display: block;" >
        <img class="addr_bg pa" src="/images/pop3_bg.png" alt="地址簿背景框"/><!--huangchun 2014-11-12-->
        <h2 class="pa">地址簿</h2>
        <div class='list-ul-hc pa list-ul-hc-ab address-book'></div>
        <div class='menu-btn-hc menu-btn-hc-ab pa' id='m_btn'>
            <button id="add-contact" class="add_hc w150h50 pa"></button>
            <button id="share-contact" class="share_hc w150h50 pa"></button>
        </div>
    </div>
    <!-- 地址簿end -->
</div>
<script src="/js/jquery-1.9.0.min.js"></script>
<script src="/js/google.fastbutton.js"></script>
<script src="/js/jquery.google.fastbutton.js"></script>
<script src="/js/common.js?<?php echo $tag; ?>"></script>
<script src="/js/address-book.js?<?php echo $tag; ?>"></script>
</body>
</html>
