<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>趣邮明信片</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <link rel="stylesheet" href="/css/reset.css?<?php echo $tag; ?>"/>
    <link rel="stylesheet" href="/css/addressbook.css?<?php echo $tag; ?>"/>
</head>
<body>
<input type="hidden" id="var-user-name" value="<?php echo $userName; ?>" />

<div class="popbox pa hide">
    <div class="pop-wrapper hint">
        <h2 class="pop-title"></h2>
        <p class="pop-message"></p>
        <button class="pop-close-button">关闭</button>
    </div>
</div>

<div class="container">
    <div id="pop-address" class="pop2 pop2-ab pa"  style="background-color: white;">
        <div class="bgK pa" style="top:10px;"><img src="/images/fill_contact_bg.png?<?php echo $tag; ?>" alt=""/></div>
        <div class="edit_title pa" style="top:35px;margin-left: -120px;">关注趣邮明信片并在此填写您的收信地<br>址就有可能收到对方寄给你的明信片哦</div>
        <input class="recipient_input pa" type="text" placeholder="收件人姓名"/>
        <form name="creator">
            <select id="province_select" name="province" class="province_input pa" placeholder="省"></select>
            <select id="city_select" name="city" class="city_input pa" placeholder="市"> </select>
        </form>
        <input class="district_input pa" type="text" placeholder="区"/>
        <input class="address_input pa" type="text" placeholder="街道地址、门牌号"/>
        <input class="postcode_input pa" type="text" placeholder="邮政编码"/>
        <input class="mobile_input pa" type="text" placeholder="联系电话"/>
        <div class='menu-btn-hc pa' style="top:290px">
            <input id="pop-confirm" type="image" src="/images/complete_btn.png?<?php echo $tag; ?>" alt="确定"/>
        </div>
    </div>
</div>
<script src="/js/jquery-1.9.0.min.js"></script>
<script src="/js/google.fastbutton.js"></script>
<script src="/js/jquery.google.fastbutton.js"></script>
<script src="/js/common.js?<?php echo $tag; ?>"></script>
<script src="/js/locality-select.js?<?php echo $tag; ?>"></script>
<script src="/js/filladdress.js?<?php echo $tag; ?>"></script>
<script language="javascript" >
</script>
</body>
</html>
