<html>
<head lang="en">
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>趣邮明信片</title>
    <script src="/js/jquery-1.9.0.min.js"></script>
    <script src="http://res.wx.qq.com/open/js/jweixin-1.0.0.js"></script>
    <script src="/js/common.js"></script>
    <script src="/js/activity-intro.js?<?php echo $JS_TAG; ?>"></script>
    <?php $actName = $this->escapeHtml($actName); ?>
<?php if ($this->resolver("postcard/activity/include/{$actName}.header.phtml")): ?>    
    <?php echo $this->partial("postcard/activity/include/{$actName}.header.phtml", array()); ?>
<?php endif; ?>
</head>
<body>
    <!-- var begin -->
    <input type="hidden" id="global-var" 
        data-username="<?php echo $this->escapeHtml($userName); ?>"
        data-accesstoken="<?php echo $accessToken; ?>" />
    <!-- var end -->

    <?php echo $this->partial("postcard/activity/include/{$actName}.phtml", array()); ?>
</body>
</html>
