<?php
ini_set("display_errors", true);

include_once(dirname(__FILE__)."/../../../../Wxpay/view/wxpay/wxpay/WxPayHelper.php");

$wxPayHelper = new WxPayHelper();
?>

<html manifest="/safari.manifest"><!--  -->
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <script language="javascript">

            document.addEventListener('WeixinJSBridgeReady', function onBridgeReady() {
                editShareAddress();
            });

            function editShareAddress() {
                WeixinJSBridge.invoke(
                    'editAddress', <?php echo $wxPayHelper->create_addr_package($token, $url) ?>, 
                    function(res) {
                        //若res 中所带的返回值不为空,则表示用户选择该返回值作为收货地址。否则若返回空,则表示用户取消了这一次编辑收货地址。
                        // alert(res.err_msg + "  " + res.err_desc);
                        // alert(res.proviceFirstStageName + res.addressCitySecondStageName + res.addressCountiesThirdStageName + res.addressDetailInfo + res.telNumber);
                    }
                );
            }

        </script>
    </head>

    <body>
        <!-- <p>url:<?php echo $url ?> </p> -->
        <!-- <p>token:<?php echo $token ?> </p> -->
        <a id="editAddress" href="javascript:editShareAddress()"><p class="title">收货地址</p></a>
    </body>
</html>
