<?php
ini_set("display_errors", true);

include_once(dirname(__FILE__)."/../../../../Wxpay/view/wxpay/wxpay/WxPayHelper.php");

$wxPayHelper = new WxPayHelper();
$wxPayHelper->setParameter("bank_type", "WX");
$wxPayHelper->setParameter("body", "趣邮明信片");
$wxPayHelper->setParameter("partner", PARTNERID);
$wxPayHelper->setParameter("out_trade_no", ''.$order->id);
$wxPayHelper->setParameter("total_fee", "5"); //  ¥0.05
$wxPayHelper->setParameter("fee_type", "1");
$wxPayHelper->setParameter("notify_url", "http://paohai.ikamobile.com/wxpay/result");
$wxPayHelper->setParameter("spbill_create_ip", "127.0.0.1");
$wxPayHelper->setParameter("input_charset", "UTF-8");

?>

<html manifest="/safari.manifest"><!--  -->
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
        <link rel="stylesheet" href="/css/jquery.mobile-1.3.1.min.css" />
        <link rel="stylesheet" href="/css/paohai.css?<?php echo $tag; ?>" />
        <link rel="stylesheet" href="/css/address.css?<?php echo $tag; ?>" />
        <link rel="stylesheet" href="/css/jquery.shadow.css" />

    </head>

    <body>
        <div id="postcard-loader" data-role="content" align="center"><img src="/css/images/ajax-loader.gif" /></div>
        <div id="content" data-role="content" style="display:none">

            <input id="orderId" type="hidden" value=<?php echo $order->id ?> ></input>
            <input id="userName" type="hidden" value=<?php echo $order->userName ?> ></input>

            <div data-role="page" id="addressPage" data-title="收信人" class="page">

                <!--<img class="page_background blur" src=<?php echo $order->picUrl ?> ></img>-->

                <div data-role="header">
                    <a data-role="none" align="left" href="#" onclick="javascript:history.go(-1);"><IMG src="/images/small/left_arrow.png">上一步</a>
                </div>

                <div data-role="content" align="left">
                    <div id="board"></div>

                    <input id="recipientInput" data-role="none" class="ui-body-d ui-corner-all ui-shadow-inset" type="text" placeholder="收件人姓名" value=<?php echo $order->recipient ?> ></input>

                    <input id="addressInput" data-role="none" class="ui-body-d ui-corner-all ui-shadow-inset" type="text" placeholder="收件人地址" value=<?php echo $order->address ?> ></input>

                    <input id="zipcodeInput" data-role="none" class="ui-body-d ui-corner-all ui-shadow-inset" type="text" placeholder="邮政编码" value=<?php echo $order->zipCode ?> ></input>

                    <a id="saveRecipientToAddressBookBtn" class="bbtn" data-role="none" href="javascript:void(0)"><IMG class="nextbtnicon" src="/images/small/checkboxoff.png">存入地址簿</a>
                    <a id="selectRecipientFromAddressBookBtn" class="bbtn" data-role="none" href="javascript:void(0)" ><IMG class="nextbtnicon" src="/images/small/addressbook.png">从地址簿选一个</a>

                    <a id="submitAddressButton" class="abtn" data-role="none" href="javascript:void(0)" >下一步<IMG class="nextbtnicon" src="/images/small/next_btn.png"></a>

                </div>
            </div>

            <div data-role="page" id="senderPage" data-title="发信人" class="page">

                <!--<img class="page_background blur" src=<?php echo $order->picUrl ?> ></img>-->

                <div data-role="header">
                    <a data-role="none" align="left" href="#" onclick="javascript:history.go(-1);"><IMG src="/images/small/left_arrow.png">上一步</a>
                </div>

                <div data-role="content" align="left">
                    <div id="senderboard"></div>

                    <input id="senderNameInput" data-role="none" class="ui-body-d ui-corner-all ui-shadow-inset" type="text" placeholder="发件人姓名" value=<?php echo $order->senderName ?> ></input>

                    <input id="senderAddressInput" data-role="none" class="ui-body-d ui-corner-all ui-shadow-inset" type="text" placeholder="发件人地址" value=<?php echo $order->senderAddress ?> ></input>

                    <a id="saveSenderToAddressBookBtn" class="bbtn" data-role="none" href="javascript:void(0)" ><IMG class="nextbtnicon" src="/images/small/checkboxoff.png?<?php echo $tag; ?>">存入地址簿</a>
                    <a id="selectSenderFromAddressBookBtn" class="bbtn" data-role="none" href="javascript:void(0)" ><IMG class="nextbtnicon" src="/images/small/addressbook.png">从地址簿选一个</a>

                    <input id="previewButton" value="去预览" type="image" src="/images/small/preview_btn.png?<?php echo $tag; ?>"></input>
                    <input id="gotoPayButton" value="去支付" type="image" src="/images/small/pay_btn.png?<?php echo $tag; ?>" ></input>

                </div>
            </div>

            <div data-role="page" id="contactsPage" data-title="选择联系人" class="page">

                <!--<img class="page_background blur" src=<?php echo $order->picUrl ?> ></img>-->
                <h2 id="list_title_hc">地址簿</h2>
                <div data-role="content" align="left">
                    <div id="contactsList">
                    </div>
                </div>
            </div>            

            <!--[huangchun 2014-9-22]新添定位锚层-->
            <div data-role="page" id="position" data-title="YOYO定位" class="page">

                <!--<img class="page_background blur" src=http://pic.sc.chinaz.com/files/pic/pic9/201405/apic3699.jpg ></img>-->

                <div data-role="header">
                    <a data-role="none" align="left" href="#" onclick="javascript:history.go(-1);"><IMG src="/images/small/left_arrow.png">上一步</a>
                </div>

                <div data-role="content" align="left">
                    <div class="position-hc">
                        <h1>...泡海正在定位...<br>将为您贴上本地邮戳!</h1>
                        <img src="/images/earth.gif" alt="定位"/>
                        <a href="#" class="hide-hc">隐藏此层</a>
                    </div>
                </div>
            </div>
            <!--定位锚层end-->
        </div>

        <script src="/js/jquery-1.9.0.min.js"></script>
        <script src="/js/artDialog.js"></script>
        <script src="/js/jquery.mobile-1.3.1.min.js"></script>
        <script src="/js/google.fastbutton.js"></script>
        <script src="/js/jquery.google.fastbutton.js"></script>
        <script src="/js/jquery.event.move.js"></script>
        <script src="/js/jquery.shadow.js"></script>
        <script src=<?php echo "/js/util.js?$tag" ?> ></script>
        <script src=<?php echo "/js/address.js?$tag" ?> ></script> 
        <script language="javascript">

            // function editShareAddress() {
            //     WeixinJSBridge.invoke(
            //         'editAddress', < ? php echo $wxPayHelper->create_addr_package($token, $url) ? > , 
            //         function(res) {
            //             //若res 中所带的返回值不为空,则表示用户选择该返回值作为收货地址。否则若返回空,则表示用户取消了这一次编辑收货地址。
            //             document.getElementById('recipientInput').value = res.userName;
            //             document.getElementById('addressInput').value = res.proviceFirstStageName+res.addressCitySecondStageName+res.addressCountiesThirdStageName+res.addressDetailInfo;
            //             document.getElementById('zipcodeInput').value = res.addressPostalCode;
            //         }
            //     );
            // }
            function callPay() {
                WeixinJSBridge.invoke('getBrandWCPayRequest', <?php echo $wxPayHelper->create_biz_package(); ?>, payCallback);
            }

            function payCallback(res) {
                WeixinJSBridge.log(res.err_msg);
                if (res.err_msg == 'get_brand_wcpay_request:ok') { // pay success
                    self.location = "http://" + window.location.host + "/postcard/complete/" + <?php echo '"'.$order->id.'"' ?> + "?nonce=" + getNonceStr();;
                } else if (res.err_msg != 'get_brand_wcpay_request:cancel') { // fail with other reason, exclude user cancel
                    alert(res.err_msg);
                }
            }

            $(function($) {
                $("#postcard-loader").hide();
                $("#content").show();
            });
        </script>
    </body>
</html>
