<?php
ini_set("display_errors", true);

include_once("WxPayHelper.php");

$wxPayHelper = new WxPayHelper();
$wxPayHelper->setParameter("bank_type", "WX");
$wxPayHelper->setParameter("body", "泡海明信片");
$wxPayHelper->setParameter("partner", PARTNERID);
$wxPayHelper->setParameter("out_trade_no", ''.$order_id);
$wxPayHelper->setParameter("total_fee", $total_fee);
$wxPayHelper->setParameter("fee_type", "1");
$wxPayHelper->setParameter("notify_url", "http://paohai.ikamobile.com/wxpay/result");
$wxPayHelper->setParameter("spbill_create_ip", "127.0.0.1");
$wxPayHelper->setParameter("input_charset", "UTF-8");
?>

<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script language="javascript">
        document.addEventListener('WeixinJSBridgeReady', function onBridgeReady() {
            callPay();
        });

        function callPay()
        {
            WeixinJSBridge.invoke('getBrandWCPayRequest', <?php echo $wxPayHelper->create_biz_package(); ?>, function(res) {
                WeixinJSBridge.log(res.err_msg);
                if (res.err_msg == 'get_brand_wcpay_request:ok') { // pay success
                    self.location = "http://" + window.location.host + "/postcard/complete/" + <?php echo '"'.$order_id.'"' ?>;
                } else if (res.err_msg != 'get_brand_wcpay_request:cancel') { // fail with other reason, exclude user cancel
                    alert(res.err_msg);
                }
            });
        }

    </script>
</head>
<body>
    <p>泡海明信片</p>
    <p>订单号：<?php echo $order_id; ?></p>
    <a id="getBrandWCPayRequest" href="javascript:callPay()"><p class="title">点击支付</p></a>

</body>
</html>
