<?php
ini_set("display_errors", true);

include_once("WxPayHelper.php");

$wxPayHelper = new WxPayHelper();
$wxPayHelper->setParameter("bank_type", "WX");
$wxPayHelper->setParameter("body", "趣邮明信片");
$wxPayHelper->setParameter("partner", PARTNERID);
$wxPayHelper->setParameter("out_trade_no", ''.$order->id);
$wxPayHelper->setParameter("total_fee", "5"); //  ¥0.05
$wxPayHelper->setParameter("fee_type", "1");
$wxPayHelper->setParameter("notify_url", "http://quyou.ikamobile.com/wxpay/result");
$wxPayHelper->setParameter("spbill_create_ip", "127.0.0.1");
$wxPayHelper->setParameter("input_charset", "UTF-8");


?>

<html manifest="/safari.manifest">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/css/jquery.mobile-1.3.1.min.css" />
        <link rel="stylesheet" href="/css/paohai.css?<?php echo $tag; ?>" />
        <link rel="stylesheet" href="/css/pay.css?<?php echo $tag; ?>" />
        <script src="/js/jquery-1.9.0.min.js"></script>
        <script src="/js/artDialog.js"></script>
        <script src="/js/jquery.mobile-1.3.1.min.js"></script>
        <script src="/js/google.fastbutton.js"></script>
        <script src="/js/jquery.google.fastbutton.js"></script>
        <script src=<?php echo "/js/util.js?$tag" ?> ></script>
        <script src=<?php echo "/js/pay.js?$tag" ?> ></script>

        <script language="javascript">

            function callPay() {
                WeixinJSBridge.invoke('getBrandWCPayRequest', <?php echo $wxPayHelper->create_biz_package(); ?>, payCallback);
            }

            function payCallback(res) {
                WeixinJSBridge.log(res.err_msg);
                if (res.err_msg == 'get_brand_wcpay_request:ok') { // pay success
                    self.location = "http://" + window.location.host + "/postcard/complete/" + <?php echo '"'.$order->id.'"' ?> + "?nonce=" + getNonceStr();;
                } else if (res.err_msg != 'get_brand_wcpay_request:cancel') { // fail with other reason, exclude user cancel
                    alert(res.err_msg);
                }
            }
        </script>
    </head>

    <body>
        <div id="content" data-role="content">

            <div data-role='page' id='paymentPage' data-title='支付' class='page'>

                <!--<img class="page_background blur" src=<?php echo $order->picUrl ?> ></img>-->

                <div data-role="header">
                    <a data-role="none" align="left" href="#" onclick="javascript:history.go(-1);"><IMG src="/images/small/left_arrow.png">上一步</a>
                </div>

                <div data-role="content" align="center">
                    <p style="text-shadow:none; ">订单号：<?php echo $order->id; ?></p>
                    <p>通过兴业银行支付可获得4元返现（直接退款）</p>
                    <input id="submitPaymentButton1" value="立即付款 5 元" type="image" src="/images/small/pay_btn.png" onclick="callPay()"></input>
                </div>
            </div>

        </div>
    </body>
</html>
