<?php
ini_set("display_errors", true);

include_once(dirname(__FILE__)."/../../../../Wxpay/view/wxpay/wxpay/WxPayPubHelper/js_api_call.php");

if (stripos($_SERVER['SERVER_NAME'], 'ikamobile.com')) {
    $jsApiParameters = WXJsPay::getPayPara(WXJsPay::JS_API_CALL_PREVIEW_URL, $order->id);
} else {
    $jsApiParameters = "'simulator'";
}
?>

<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>趣邮明信片</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <link rel="stylesheet" href="/css/reset.css"/>
    <link rel="stylesheet" href="/css/common.css"/>
</head>
<body>
<div class="loadMask pa">
    <img src="/images/loading.gif" alt="loading" /><span>加载中...</span>
</div>
<input id="var-user-name" type="hidden" value="" ></input>
<input id="var-order-id" type="hidden" value="<?php echo $order->id ?>" ></input>
<input id="var-user-picurl" type="hidden" value="<?php echo $order->picUrl ?>" ></input>
<input id="var-offset-x" type="hidden" value="<?php echo $order->offsetX ?>" ></input>
<input id="var-offset-y" type="hidden" value="<?php echo $order->offsetY ?>" ></input>
<input id="var-template-index" type="hidden" value="<?php echo $order->templateId ?>" ></input>
<input id="var-salutation" type="hidden" value="<?php echo $order->salutation ?>" ></input>
<input id="var-message" type="hidden" value="<?php echo $order->message ?>" ></input>
<input id="var-signature" type="hidden" value="<?php echo $order->signature ?>" ></input>
<input id="var-recipient" type="hidden" value="<?php echo $order->recipient ?>" ></input>
<input id="var-address" type="hidden" value="<?php echo $order->address ?>" ></input>
<input id="var-zipcode" type="hidden" value="<?php echo $order->zipCode ?>" ></input>
<input id="var-mobile" type="hidden" value="<?php echo $order->recipientMobile ?>" ></input>
<input id="var-voice-media-id" type="hidden" value="<?php echo $order->voiceMediaId ?>" ></input>
<input id="var-postmark-index" type="hidden" value="<?php echo $order->postmarkId ?>" ></input>

<div class="container">
    <!--菜单条-->
    <div class="menuBar h42 pr">
        <a id="prev-step" href="#" class="changeImg pa">上一步</a>
    </div>
    <!--面包屑-->
    <div class="breadNav" id="crumbs">
        <ul class="frsb">
            <li><a href="#1" class="w99p">第一步</a></li>
            <li><a href="#2" class="w99p">第二步</a></li>
            <li><a href="#3" class="current w100p">第三步</a></li>
        </ul>
    </div>

    <div class="page3 pa">
        <div class="bigImg_a pa" id="imageFace">
            <div class="bgLayer_a pa"><img class="bgLayer_img_a"></div>
            <div class="imgLayer_a pa">
                <!-- <img class="imgLayer_img_a"> -->
                <canvas id="previewUserImg" style="position:absolute; left:0"></canvas>
            </div>
        </div>
        <div class="frontCover pa" id="textFace" style="display:none;">
            <img src="/images/front_cover.png" alt="文字面背景"/>
            <div class="textCover pa">
                <div id="zipcodePreview"></div>
                <div id="salutationPreview"></div>
                <div id="messagePreview"></div>
                <div id="signaturePreview"></div>
                <div id="addressPreview"></div>
                <div id="recipientPreview"></div>
                <img id="qrImagePreview" src="/images/small/qrimg.png" style="display:none;">
                <img id="postmarkPreview" src="" style="display:none;">
            </div>
        </div>

        <input type="image" id="editButton" class="back_modify getZ pa w150h50" src="/images/fanhuixiugai.png" alt="返回修改"/>
        <input type="image" id="gotoPayButton" class="pay_conf pa w150h50" src="/images/querenzhifu.png" alt="确认支付"/>
        <input type="image" id="toggleFaceButton" class="pa w95" style="left:50%;top:260px;margin-left:10px;height:54px;z-index:15;" src="/images/turn_around_btn.png" alt="翻转"/>
    </div>
</div>
<script src="/js/jquery-1.9.0.min.js"></script>
<script src="/js/google.fastbutton.js"></script>
<script src="/js/jquery.google.fastbutton.js"></script>
<script src="/js/classie.js"></script>
<script src="/js/common.js"></script>
<script src="/js/postcard.js"></script>
<script src="/js/preview.js"></script>
<script language="javascript">
    //调用微信JS api 支付
    function jsApiCall()
    {
        WeixinJSBridge.invoke(
            'getBrandWCPayRequest',
            <?php echo $jsApiParameters; ?>,
            function(res){
                if (res.err_msg == 'get_brand_wcpay_request:ok') { // pay success
                    self.location = "http://" + window.location.host + "/postcard/complete/" + <?php echo '"'.$order->id.'"' ?> + "?nonce=" + HC.getNonceStr();
                } else if (res.err_msg != 'get_brand_wcpay_request:cancel') { // fail with other reason, exclude user cancel
                    alert(res.err_msg);
                }
            }
        );
    }

</script>
</body>
</html>
