<?php
ini_set("display_errors", true); 
include_once(dirname(__FILE__)."/../../../../Wxpay/view/wxpay/wxpay/WxPayPubHelper/js_api_call.php");
if ($payPrice != 0) {
    $jsApiParameters = WXJsPay::getPayPara(WXJsPay::JS_API_CALL_PREVIEW_URL, $order->id, $payPrice);
}

?>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>趣邮明信片</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <link rel="stylesheet" href="/css/reset.css?<?php echo $tag; ?>"/>
    <link rel="stylesheet" href="/css/common.css?<?php echo $tag; ?>"/>
</head>
<body>
<div class="loadMask loading-image pa">
    <div><img src="/images/loading.gif" alt="loading" /><span>加载中...</span></div>
</div>
<div class="loadMask orientation-tips pa" style="display:none">
    <div><span>亲，竖屏操作体验更好哦</span></div>
</div>

<div class="container">
    <!--菜单条-->
    <div class="menuBar h42 pr">
        <a id="prev-step" href="#" class="changeImg pa">返回修改</a>
    </div>

    <div class="page3 pa">
        <div class="bigImg_a pa" id="imageFace">
            <div class="bgLayer_a pa"><img class="bgLayer_img_a"></div>
            <div class="imgLayer_a pa">
<!--                 <img class="imgLayer_img_a">-->
                <img id="previewUserImg" style="position:absolute; left:0"></img>
<!--                <canvas id="previewUserImg" style="position:absolute; left:0"></canvas>-->
            </div>
        </div>
        <div class="frontCover pa" id="textFace" style="display:none;">
            <img src="/images/small/postCardBack.jpg" alt="文字面背景" class="frontCover pa" style="top:0px;"/>
            <div class="textCover pa">
                <div id="zipcodePreview"></div>
                <div id="salutationPreview"></div>
                <div id="messagePreview"></div>
                <div id="signaturePreview"></div>
                <div id="addressPreview"></div>
                <div id="recipientPreview"></div>
                <img id="qrImagePreview" src="/images/small/qrimg.png" style="display:none;">
                <img id="stampPreview" src="/images/small/logo.jpg">
                <div id="qrImageTextPreview" style="display:none;"></div>
                <img id="postmarkPreview" src="" style="display:none;">
                <div id="postmarkCityPreview" style="display:none;"></div>
                <div id="postmarkDatePreview" style="display:none;"></div>
            </div>
        </div>

        <input type="image" id="toggleFaceButton" class="turn_around pa w150h50" src="/images/turn_around_btn.png" alt="翻转"/>
        <div><a href="#" class="postage_choice pa">平邮（2.99元/张）</a></div>
        <div><a href="#" class="express_delivery_choice pa">专递（9.99元/张）</a></div>

        <div><a href="#" class="consumer_code pa">输入消费码</a></div>
        <div><a href="#" class="total_price pa">共计2.99元</a></div>

        <input type="image" id="gotoPayButton" class="pay_conf pa" src="/images/querenzhifu.png" alt="确认支付"/>
    </div>
</div>

<div style="display: none">
    <!--<input id="var-user-name"       type="hidden" value="" />-->
    <input id="var-order-id"        type="hidden" value="<?php echo $order->id ?>" />
    <input id="var-user-picurl"     type="hidden" value="<?php echo $order->picUrl ?>" />
    <input id="var-offset-x"        type="hidden" value="<?php echo $order->offsetX ?>" />
    <input id="var-offset-y"        type="hidden" value="<?php echo $order->offsetY ?>" />
    <input id="var-template-index"  type="hidden" value="<?php echo $order->templateId ?>" />
    <input id="var-salutation"      type="hidden" value="<?php echo $order->salutation ?>" />
    <input id="var-message"         type="hidden" value="<?php echo $order->message ?>" />
    <input id="var-signature"       type="hidden" value="<?php echo $order->signature ?>" />
    <input id="var-recipient"       type="hidden" value="<?php echo $order->recipient ?>" />
    <input id="var-address"         type="hidden" value="<?php echo $order->address ?>" />
    <input id="var-zipcode"         type="hidden" value="<?php echo $order->zipCode ?>" />
    <input id="var-mobile"          type="hidden" value="<?php echo $order->recipientMobile ?>" />
    <input id="var-voice-media-id"  type="hidden" value="<?php echo $order->voiceMediaId ?>" />
    <input id="var-postmark-index"  type="hidden" value="<?php echo $order->postmarkId ?>" />
    <input id="var-city"            type="hidden" value="<?php echo $city ?>" />
    <input id="var-template"        type="hidden" data-rotate="<?php echo $template["rotate"]; ?>" data-thumb="<?php echo $template["thumbUrl"]; ?>" />
</div>
<script src="/js/jquery-1.9.0.min.js"></script>
<script src="/js/google.fastbutton.js"></script>
<script src="/js/jquery.google.fastbutton.js"></script>
<script src="/js/classie.js"></script>
<script src="/js/common.js?<?php echo $tag; ?>"></script>
<script src="/js/postcard.js?<?php echo $tag; ?>"></script>
<script src="/js/preview.js?<?php echo $tag; ?>"></script>
<script language="javascript">
    //调用微信JS api 支付
    function jsApiCall()
    {
<?php if ($payPrice == 0): ?>
        self.location = "http://" + window.location.host + "/postcard/complete/" + <?php echo '"'.$order->id.'"' ?> + "?nonce=" + HC.getNonceStr();
<?php else: ?>
        WeixinJSBridge.invoke(
            'getBrandWCPayRequest',
            <?php echo $jsApiParameters; ?>,  
            function(res){
                if (res.err_msg == 'get_brand_wcpay_request:ok') { // pay success
                    self.location = "http://" + window.location.host + "/postcard/complete/" + <?php echo '"'.$order->id.'"' ?> + "?nonce=" + HC.getNonceStr();
                } else if (res.err_msg != 'get_brand_wcpay_request:cancel') { // fail with other reason, exclude user cancel
                    alert(res.err_msg);
                }
            }
        );
<?php endif ?>
    }

</script>
</body>
</html>
