<?php
ini_set("display_errors", true);

include_once(dirname(__FILE__)."/../../../../Wxpay/view/wxpay/wxpay/WxPayHelper.php");

$wxPayHelper = new WxPayHelper();
$wxPayHelper->setParameter("bank_type", "WX");
$wxPayHelper->setParameter("body", "趣邮明信片");
$wxPayHelper->setParameter("partner", PARTNERID);
$wxPayHelper->setParameter("out_trade_no", ''.$order->id);
$wxPayHelper->setParameter("total_fee", "5"); //  ¥0.05
$wxPayHelper->setParameter("fee_type", "1");
$wxPayHelper->setParameter("notify_url", "http://paohai.ikamobile.com/wxpay/result");
$wxPayHelper->setParameter("spbill_create_ip", "127.0.0.1");
$wxPayHelper->setParameter("input_charset", "UTF-8");

?>

<html manifest="/safari.manifest"><!--  -->
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/css/jquery.mobile-1.3.1.min.css" />
        <link rel="stylesheet" href="/css/paohai.css" />
        <link rel="stylesheet" href="/css/preview.css" />
        <link rel="stylesheet" href="/css/jquery.shadow.css" />

    </head>

    <body>
        <div id="postcard-loader" data-role="content" align="center"><img src="/css/images/ajax-loader.gif" /></div>
        <div id="content" data-role="content" style="display:none">
            <input id="orderId" type="hidden" value=<?php echo $order->id ?> ></input>

            <input id="picUrl" type="hidden" value=<?php echo $order->picUrl ?> ></input>
            <input id="templateIndex" type="hidden" value=<?php echo $order->templateId ?> ></input>
            <input id="offsetX" type="hidden" value=<?php echo $order->offsetX ?> ></input>
            <input id="offsetY" type="hidden" value=<?php echo $order->offsetY ?> ></input>

            <input id="salutation" type="hidden" value=<?php echo $order->salutation ?> ></input>
            <input id="message" type="hidden" value=<?php echo $order->message ?> ></input>
            <input id="signature" type="hidden" value=<?php echo $order->signature ?> ></input>

            <input id="recipient" type="hidden" value=<?php echo $order->recipient ?> ></input>
            <input id="address" type="hidden" value=<?php echo $order->address ?> ></input>
            <input id="zipcode" type="hidden" value=<?php echo $order->zipCode ?> ></input>
            <input id="mobile" type="hidden" value=<?php echo $order->recipientMobile ?> ></input>

            <div data-role="page" id="previewPage" data-title="预览" class="page">
                <!--<img class="page_background blur" src="<?php echo $order->picUrl; ?>">-->

                <div data-role="header">
                    <a data-role="none" align="left" href="#" onclick="javascript:history.go(-1);"><IMG src="/images/small/left_arrow.png">上一步</a>
                </div>

                <div data-role="content" align="center">
                    <div class="postcard" style="height: 60%">
                        <canvas id="previewUserImg" style="position:absolute; left:0"></canvas>
                    </div>
                    <img id="previewTemplateImg" class="postcard" style="height: 60%"></img>

                    <div style="top:450px; width:320px; height:200px; position:absolute; left: 50%; margin-left: -160px;">
                        <img id="postcardback" src="/images/small/postCardBack.png"></img>
                        <div style="position:absolute; width:320px; height:200px; left:0">
                            <div id="zipcodePreview"></div>
                            <div id="messagePreview"></div>
                            <div id="signaturePreview"></div>
                            <div id="addressPreview"></div>
                            <div id="recipientPreview"></div>
                        </div>
                    </div>


                    <input id="editButton" value="返回修改" type="image" src="/images/small/edit_btn.png"></input>
                    <input id="gotoPayButton" value="确认支付" type="image" src="/images/small/pay_confirm_btn.png"></input>

                </div>
            </div>
        
        </div>

        <script src="/js/jquery-1.9.0.min.js"></script>
        <script src="/js/artDialog.js"></script>
        <script src="/js/jquery.mobile-1.3.1.min.js"></script>
        <script src="/js/google.fastbutton.js"></script>
        <script src="/js/jquery.google.fastbutton.js"></script>
        <!--  <script src="/js/jquery.shadow.js"></script>  -->
        <script src=<?php echo "/js/util.js?$tag" ?> ></script>
        <script src=<?php echo "/js/preview.js?$tag" ?> ></script>
        <script type="text/javascript">

            function callPay() {
                WeixinJSBridge.invoke('getBrandWCPayRequest', <?php echo $wxPayHelper->create_biz_package(); ?>, payCallback);
            }

            function payCallback(res) {
                WeixinJSBridge.log(res.err_msg);
                if (res.err_msg == 'get_brand_wcpay_request:ok') { // pay success
                    self.location = "http://" + window.location.host + "/postcard/complete/" + <?php echo '"'.$order->id.'"' ?> + "?nonce=" + getNonceStr();;
                } else if (res.err_msg != 'get_brand_wcpay_request:cancel') { // fail with other reason, exclude user cancel
                    alert(res.err_msg);
                }
            }
        
            $(function($) {
                $("#postcard-loader").hide();
                $("#content").show();
            });
        </script>
    </body>
</html>
