<!DOCTYPE html  >
<html>
    <head>
        <meta charset="UTF-8">
        <title>趣邮明信片</title>
        <meta http-equiv="content-type" content="text/html; charset=utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/css/common.css?<?php echo $tag; ?>"/>
    </head>

    <body>
        <div class="page4">
            <div data-role="page" id="completePage" data-title="完成" class="page">
                <div data-role="content" align="center">
                    <div class="main_text pa">支付成功</div>
                    <input type="image" class="goto_orderlist pa" src="/images/querenzhifu.png" alt="去我的订单看看"/>
                    <input type="image" class="share_btn pa" src="/images/querenzhifu.png" alt="分享"/>
                </div>
            </div>
        </div>
    </body>

    <div style="display: none">
        <input id="var-order-id" type="hidden" value=<?php echo $order->orderId ?> >
        <input id="var-user-name" type="hidden" value=<?php echo $order->userName ?> >
    </div>

    <script src="/js/jquery-1.9.0.min.js"></script>
    <script src="/js/google.fastbutton.js"></script>
    <script src="/js/jquery.google.fastbutton.js"></script>
    <script src="http://res.wx.qq.com/open/js/jweixin-1.0.0.js"></script>
    <script language="javascript">
        wx.config({
            debug: false,
            appId: '<?php echo $jsApiSignPackage["appId"]; ?>',
            timestamp:  <?php echo $jsApiSignPackage["timestamp"];?>,
            nonceStr:  '<?php echo $jsApiSignPackage["nonceStr"];?>',
            signature: '<?php echo $jsApiSignPackage["signature"];?>',
            jsApiList: ['onMenuShareTimeline', 'onMenuShareAppMessage']
        });
    </script>
    <script src=<?php echo '"/js/complete.js?' . $tag . '"'; ?> ></script>
</html>
