<!DOCTYPE html  >
<html>
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/css/common.css?<?php echo $tag; ?>"/>
    </head>

    <body>
        <div class="page4">
            <div data-role="page" id="completePage" data-title="完成" class="page">
                <div data-role="content" align="center">
                    <div class="main_text pa">支付成功</div>
                    <input type="image" class="goto_orderlist pa" src="/images/querenzhifu.png" alt="去我的订单看看"/>
                    <input type="image" class="share_btn pa" src="/images/querenzhifu.png" alt="分享"/>
                </div>
            </div>
        </div>
    </body>

    <input id="orderId" type="hidden" value=<?php echo $orderId ?> >
    <script src="/js/jquery-1.9.0.min.js"></script>
    <script src=<?php echo '"/js/complete.js?' . $tag . '"'; ?> ></script>
</html>
