<!DOCTYPE html  >
<html manifest="/safari.manifest"><!--    -->
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/css/jquery.mobile-1.3.1.min.css" />
        <script src="/js/jquery-1.9.0.min.js"></script>
        <script src="/js/jquery.mobile-1.3.1.min.js"></script>
        <script src=<?php echo '"/js/util.js?' . $tag . '"'; ?> ></script>`
        <script src=<?php echo '"/js/complete.js?' . $tag . '"'; ?> ></script>
    </head>

    <body>
        <div id="content" data-role="content">

            <input id="orderId" type="hidden" value=<?php echo $orderId ?> ></input>

            <div data-role="page" id="completePage" data-title="完成" class="page">
                <div data-role="content" align="center">
                    <h3>明信片创建成功，我们将尽快为你邮寄！</h3>

                    <div class="bshare-custom">
                        <a title="分享到QQ空间" class="bshare-qzone"></a>
                        <a title="分享到新浪微博" class="bshare-sinaminiblog"></a>
                        <a title="分享到腾讯微博" class="bshare-qqmb"></a>
                        <!-- <a title="分享到QQ" class="bshare-qqim"></a> -->
                    </div>

                    <script type="text/javascript" charset="utf-8" src="http://static.bshare.cn/b/buttonLite.js#uuid=<你的UUID>&style=-1"></script>
                    <script type="text/javascript" charset="utf-8" src="http://static.bshare.cn/b/bshareC3.js"></script>
                </div>
            </div>

        </div>
    </body>
</html>
