<?php
$title = 'Postcard contacts';
$this->headTitle($title);
?>

<head>
    <meta http-equiv="content-type" content="text/html;charset=utf-8">

    <script language="javascript">
    function deleteDiv(ele){
     ele.parentNode.parentNode.removeChild(ele.parentNode);
    }
    </script>
</head>

<body>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <table class="table">
    <tr>
        <th>userName</th>
        <th>contactName</th>
        <th>address</th>
        <th>zipCode</th>
    </tr>
    <?php foreach ($contacts as $contact) : ?>
    <tr>
        <td><?php echo $this->escapeHtml($contact->userName);?></td>
        <td><?php echo $this->escapeHtml($contact->contactName);?></td>
        <td><?php echo $this->escapeHtml($contact->address);?></td>
        <td><?php echo $this->escapeHtml($contact->zipCode);?></td>
    </tr>
    <?php endforeach; ?>
    </table>
</body>