<html manifest="/safari.manifest"><!--  -->
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/css/jquery.mobile-1.3.1.min.css" />
        <link rel="stylesheet" href="/css/paohai.css?<?php echo $tag; ?>" />
        <link rel="stylesheet" href="/css/editmessage.css?<?php echo $tag; ?>" />
        <link rel="stylesheet" href="/css/jquery.shadow.css" />
        <script src="/js/jquery-1.9.0.min.js"></script>
        <script src="/js/artDialog.js"></script>
        <script src="/js/jquery.mobile-1.3.1.min.js"></script>
        <script src="/js/google.fastbutton.js"></script>
        <script src="/js/jquery.google.fastbutton.js"></script>
        <script src=<?php echo "/js/util.js?$tag" ?> ></script>
        <script src=<?php echo "/js/editMessage.js?$tag" ?> ></script>
    </head>

    <body>
        <div id="content" data-role="content">
            <input id="orderId" type="hidden" value=<?php echo $order->id ?> ></input>
            <input id="voiceMediaId" type="hidden" value=<?php echo $order->voiceMediaId ?> ></input>

            <div data-role="page" id="messagePage" data-title="留言" class="page">
                <!--<img class="page_background blur" src=<?php echo $order->picUrl ?> ></img>-->

                <div data-role="header">
                    <a data-role="none" align="left" href="#" onclick="javascript:history.go(-1);"><IMG src="/images/small/left_arrow.png">上一步</a>
                </div>

                <div data-role="content" align="left">
                    <div id="board"></div>

                    <input id="salutationInput" data-role="none" class="ui-body-d ui-corner-all ui-shadow-inset" type="text" placeholder="亲爱的盆友" value=<?php echo $order->salutation ?> ></input>
                    <label id="messageInputHint">少于160字</label>
                    <div id="messageWrap">
                        <textarea id="messageInput" rows="3" cols="20" placeholder="我想说..."><?php echo $order->message ?></textarea>
                    </div>
                    <input id="signatureInput" data-role="none" class="ui-body-d ui-corner-all ui-shadow-inset" type="text" placeholder="我的名字" value=<?php echo $order->signature ?> ></input>

                    <input id="voiceMessageButton" type="image" src="/images/small/voice_btn.png"></input>
                    <input id="playVoiceMessageButton" type="image" src="/images/small/play_voice_btn.png"></input>

                    <div style="vertical-align:middle;"><a id="submitMessageButton" class="abtn" data-role="none" href="javascript:void(0)" >下一步<IMG class="nextbtnicon" src="/images/small/next_btn.png"></a></div>

                </div>
            </div>
        </div>
    </body>
</html>
