<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>页面2</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <link rel="stylesheet" href="/css/reset.css"/>
    <link rel="stylesheet" href="/css/common.css"/>
</head>
<body>
<input id="var-user-name" type="hidden" value="" />
<input id="var-order-id" type="hidden" value="" />
<input id="var-user-picurl" type="hidden" value="/images/test_img.jpg" />
<input id="var-offset-x" type="hidden" value="0" />
<input id="var-offset-y" type="hidden" value="0" />
<input id="var-template-index" type="hidden" value="1" />
<input id="var-template-rotate-index" type="hidden" value="2" />
<div class="container">
    <!--菜单条-->
    <div class="menuBar h42">
        <a href="#" class="changeImg">更换图片</a>
        <a href="#" class="next">下一步</a>
    </div>
    <!--面包屑-->
    <div class="breadNav" id="crumbs">
        <ul class="frsb">
            <li><a href="#1">第一步</a></li>
            <li><a href="#2" class="current">第二步</a></li>
            <li><a href="#3">第三步</a></li>
        </ul>
    </div>
    <div class="page2 fg1 ovfw pr" id="page2">
        <div class="bgK pa"><img src="/images/bg.gif"></div>
        <div class="infoWrap pa">
            <div class="youzhen pa">
                <em></em><em></em><em></em><em></em><em></em><em class="mr0"></em>
            </div>
            <div class="youchuo w80h80 pa"><img class="w80h80" id="post_stamp" src="/images/youchuo2.png"></div>
            <div class="shoujianren pa"><input class="shoujianInput" type="text" placeholder="收件人信息"/></div>
        </div>
        <textarea class="pa zhufu" name="祝福语" id="liuyan" cols="30" rows="10" placeholder="祝福语..."></textarea>
        <label class="lab1 pa">少于500字</label>
        <input type="image" id="getJ" class="getJ pa w150h50" src="/images/r.gif" alt="获取纪念戳"/>
        <input type="image" id="getZ" class="getZ pa w150h50" src="/images/y.gif" alt="获取坐标戳"/>
    </div>

    <!--弹出窗1-->
    <div class="pop1 pa hide">
        <div class="bgK pa"><img src="/images/youchuo-bg.png" alt="邮戳盒背景"/></div>
        <label class="lab2 pa">从邮戳盒子里选一个</label>
        <div class="youchuoWraper pa">
            <a href="#1"><img src="/images/youchuo2.png" alt="邮戳"/><i></i></a>
            <a href="#2"><img src="/images/youchuo2.png" alt="邮戳"/><i></i></a>
            <a href="#3"><img src="/images/youchuo2.png" alt="邮戳"/><i></i></a>
            <a href="#4"><img src="/images/youchuo2.png" alt="邮戳"/><i></i></a>
            <a href="#5" class="on"><img src="/images/youchuo2.png" alt="邮戳"/><i></i></a>
            <a href="#6"><img src="/images/youchuo2.png" alt="邮戳"/><i></i></a>
        </div>
        <input class="youchuo_confirm pa" type="image" src="/images/youchuo-sure.png" alt="确定"/>
    </div>

    <!--弹出窗2-->
    <div class="pop2 pa hide">
        <div class="bgK pa"><img src="/images/youchuo-bg.png" alt="邮戳盒背景"/></div>
        <input class="to_who pa" type="text" placeholder="收件人"/>
        <input class="postcode pa" type="text" placeholder="邮编"/>
        <textarea class="to_address pa" name="收件人地址" cols="30" rows="10" placeholder="收件人地址"></textarea>
        <div class="menu pa">
            <a href="#" class="save_add in">存入地址簿</a>
            <button class="go_add">去地址簿抓一个 ></button>
        </div>
        <input class="youchuo_confirm pa" type="image" src="/images/youchuo-sure.png" alt="确定"/>
    </div>

    <!--弹出窗3-->
    <div class="pop3 pa hide">
        <div class="bgK pa"><img src="/images/bg3.png" alt="邮戳盒背景"/></div>
        <input class="to_who pa" type="text" placeholder="TA的昵称"/>
        <textarea class="liuyan pa" name="你想对TA说的话" cols="30" rows="10" placeholder="你想你对TA说的话..."></textarea>
        <div class="menu pa">
            <input class="voice_btn" type="image" src="/images/voice_icon.gif" alt="TTS" />
            <input class="myName" type="text" placeholder="我的昵称" />
            <!--<input class="go_add" type="text" placeholder="我的昵称"/>-->
        </div>
        <input class="youchuo_confirm pa" type="image" src="/images/youchuo-sure.png" alt="确定"/>
    </div>
</div>
<script src="/js/classie.js"></script>
<script src="/js/page2.js"></script>
</body>
</html>
