<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>趣邮明信片</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <link rel="stylesheet" href="/css/reset.css?<?php echo $tag; ?>"/>
    <link rel="stylesheet" href="/css/common.css?<?php echo $tag; ?>"/>
</head>
<body>
<div class="loadMask loading-image pa">
    <div><img src="/images/loading.gif" alt="loading" /><span>加载中...</span></div>
</div>
<div class="loadMask orientation-tips pa" style="display:none">
    <div><span>亲，竖屏操作体验更好哦</span></div>
</div>
<div class="loadMask voice-tips pa" style="display:none">
    <div><img src="/images/voice_tip.png" alt="语音留言提示" style="width: 100%; height:auto;"/></div>
</div>
<div class="container">
    <!--菜单条-->
    <div class="menuBar h42 pr">
        <a id="prev-step" href="#" class="changeImg pa">上一步</a>
        <a id="next-step" href="#" class="next pa">下一步</a>
    </div>
    <!--面包屑-->
    <div class="breadNav" id="crumbs">
        <ul class="frsb">
            <li><a href="#1" class="w99p">第一步</a></li>
            <li><a href="#2" class="current w99p">第二步</a></li>
            <li><a href="#3" class="w100p">第三步</a></li>
        </ul>
    </div>
    <div class="page2 fg1 ovfw pr" id="page2">
        <div class="bgK pa"><img src="/images/bg.gif"></div>
        <div class="infoWrap pa">
            <div class="youzhen pa">
                <em></em><em></em><em></em><em></em><em></em><em class="mr0"></em>
            </div>
            <div class="youchuo w80h80 pa"><img class="w80h80" id="post_stamp" src="/images/postmark/small/youchuo2.png"></div>
            <div class="shoujianren pa"><input class="shoujianInput" type="text" placeholder="收件人信息"/></div>
        </div>
        <textarea class="pa zhufu" name="祝福语" id="liuyan" cols="30" rows="10" placeholder="祝福语..."></textarea>
        <label class="lab1 pa">少于112字</label>
        <input type="image" id="memory-stamp-button" class="getJ pa w150h50" src="/images/y.gif" alt="获取纪念戳"/>
        <input type="image" id="latlng-button" class="getZ pa w150h50" src="/images/r.gif" alt="获取坐标戳"/>
    </div>

    <!--弹出窗1 邮戳盒子-->
    <div class="pop1 pa hide">
        <div class="bgK pa"><img src="/images/postmark/small/youchuo-bg.png" alt="邮戳盒背景"/></div>
        <label class="lab2 pa">从邮戳盒子里选一个</label>
        <div class="youchuoWraper pa">

        <?php if ($order->activityId == 105): ?>  <!--甜言蜜语-->
            <a data-index="<?php echo 105; ?>" href="#1"><img src="/images/postmark/small/youchuo<?php echo 105; ?>.png" alt="邮戳"/><i></i></a>
        <?php else: ?>
            <?php for($i = 0; $i < 9; $i++): ?>
                <a data-index="<?php echo $i; ?>" href="#1"><img src="/images/postmark/small/youchuo<?php echo $i; ?>.png" alt="邮戳"/><i></i></a>
            <?php endfor; ?>
        <?php endif; ?>
        </div>
        <input id="pop1_conf" class="youchuo_confirm pa" type="image" src="/images/postmark/small/youchuo-sure.png" alt="确定"/>
    </div>

    <!--弹出窗2 收件人信息-->
    <div class="pop2 pa hide">
        <div class="bgK pa"><img src="/images/postmark/small/youchuo-bg.png" alt="邮戳盒背景"/></div>
        <input class="recipient_input pa" type="text" placeholder="收件人姓名"/>
        <form name="creator">
            <select id="province_select" name="province" class="province_input pa" placeholder="省"></select>
            <select id="city_select" name="city" class="city_input pa" placeholder="市"> </select>
        </form>
        <input class="address_input pa" type="text" placeholder="街道地址、门牌号"/>
        <input class="postcode_input pa" type="text" placeholder="邮政编码"/>
        <input class="mobile_input pa" type="text" placeholder="联系电话"/>

        <div class="menu pa">
            <a href="#" class="save_add in">存入地址簿</a>
            <button class="go_add">去地址簿抓一个</button>
        </div>
        <input id="pop2_conf" class="youchuo_confirm pa" type="image" src="/images/postmark/small/youchuo-sure.png" alt="确定"/>
    </div>

    <!--弹出窗3 留言-->
    <div class="pop3 pa hide">
        <div class="bgK pa"><img src="/images/bg3.png" alt="邮戳盒背景"/></div>
        <input class="recipient_input pa" type="text" placeholder="TA的昵称"/>
        <textarea class="liuyan pa" maxlength="112" name="你想对TA说的话" cols="30" rows="10" placeholder="你想你对TA说的话..."></textarea>
        <div class="menu pa">
            <input class="voice_btn" type="image" src="/images/voice_icon.gif" alt="TTS" />
            <input class="play_voice_btn" type="image" src="/images/speaker.gif" alt="TTS" />
            <input class="myName" type="text" placeholder="我的昵称" />
            <!--<input class="go_add" type="text" placeholder="我的昵称"/>-->
        </div>
        <input id="pop3_conf" class="youchuo_confirm pa" type="image" src="/images/postmark/small/youchuo-sure.png" alt="确定"/>
    </div>

    <!-- address template -->
    <div id="address-template" style="display:none">
        <ul>
            <li><i>姓名：</i><span class='name-hc'></span></li>
            <li><i>地址：</i><span class='addr-hc'></span></li>
            <li><i>邮编：</i><span class='post-hc'></span></li>
            <a href='#' class='sel-btn-hc'></a>
        </ul>
    </div>

    <!-- 地址簿 -->
    <div class='list-wrap-hc pa' id='address-book' style="display:none">
        <img class="addr_bg pa" src="/images/pop3_bg.png" alt="地址簿背景框"/>
        <h2 class="pa">地址簿</h2>
        <div class='list-ul-hc pa'></div>
        <div class='menu-btn-hc pa' id='m_btn'>
            <input type="image" id="close-address" src="/images/cancel.gif" alt="取消"/>
            <input type="image" id="sure-address" src="/images/youchuo-sure.png" alt="确定"/>
        </div>
    </div>
    <!-- 地址簿end -->

        <!-- vars begin -->
        <input id="var-order-id" type="hidden" value="<?php echo $order->id; ?>" />
        <input id="var-user-name" type="hidden" value="<?php echo $order->userName; ?>" />

        <input id="var-recipient" type="hidden" value="<?php echo $order->recipient; ?>" />
        <input id="var-address" type="hidden" value="<?php echo $order->address; ?>" />
        <input id="var-zipcode" type="hidden" value="<?php echo $order->zipCode; ?>" />
        <input id="var-mobile" type="hidden" value="<?php echo $order->recipientMobile; ?>" />

        <input id="var-salutation" type="hidden" value="<?php echo $order->salutation; ?>" />
        <input id="var-message" type="hidden" value="<?php echo $order->message; ?>" />
        <input id="var-signature" type="hidden" value="<?php echo $order->signature; ?>" />

        <input id="var-postmark-index" type="hidden" value="<?php echo $order->postmarkId !== NULL ? $order->postmarkId : "" ; ?>" />
        <input id="var-voice-media-id" type="hidden" value="<?php echo $order->voiceMediaId; ?>" />
        <input id="var-partner-id" type="hidden" value="<?php echo $order->partnerId ?: ''; ?>" />
        <input id="var-activity-id" type="hidden" value="<?php echo $order->activityId ?: ''; ?>" />
        <!-- vars end -->
</div>
<div class="popbox pa hide">
    <div class="pop-wrapper hint">
        <h2 class="pop-title"></h2>
        <p class="pop-message"></p>
        <button class="pop-close-button">关闭</button>
    </div>
</div>
<script src="/js/jquery-1.9.0.min.js"></script>
<script src="/js/classie.js?<?php echo $tag; ?>"></script>
<script src="/js/common.js?<?php echo $tag; ?>"></script>
<script src="/js/locality-select.js?<?php echo $tag; ?>"></script>
<script src="/js/postcard.js?<?php echo $tag; ?>"></script>
<script src="/js/editpostcard.js?<?php echo $tag; ?>"></script>
</body>
</html>
