<!DOCTYPE html>
<html manifest="/safari.manifest">
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <link rel="stylesheet" href="css/reset.css?<?php echo $tag; ?>"/>
    <link rel="stylesheet" href="css/common.css?<?php echo $tag; ?>"/>
</head>
<body>
<div class="container">
    <!--菜单条-->
    <div class="menuBar h42">
        <a href="#" class="changeImg" onclick="javascript:WeixinJSBridge.call('closeWindow');">更换图片</a>
        <a href="#" class="next">下一步</a>
    </div>
    <!--面包屑-->
    <div class="breadNav" id="crumbs">
        <ul class="frsb">
            <li><a href="#1" class="current">第一步</a></li>
            <li><a href="#2">第二步</a></li>
            <li><a href="#3">第三步</a></li>
        </ul>
    </div>
    <div class="page1 fc fg1 ovfw">
    <!--大图显示-->
        <div class="bigImg">
            <div class="bgLayer"><img class="bgLayer_img" src="images/small/template1.png?<?php echo $tag; ?>"></div>
            <div class="imgLayer"><img class="imgLayer_img" src="images/test_img.jpg"></div>
        </div>
        <!--模板选择按钮-->
        <div class="selectTemp h38 bc0e5a98 btlr_radius20">
            <button class="sBtn btlr_radius20" id="select_temp">选择模板</button>
        </div>
        <!--模板缩略图-->
        <div class="thumbImg h18 bc0e5a98">
            <ul class="pt20" id="thumb_ul">
            <?php for ($i = 1; $i <= 10; $i += 1): ?>
                <li><img class="thumb_imgs" src="<?php echo "/images/small/template$i.png?$tag"; ?>" title="背景缩略图<?php echo $i; ?>"</li>
            <?php endfor; ?>
            </ul>
        </div>
    </div>
</div>
<script src="/js/jquery-1.9.0.min.js"></script>
<script src="js/classie.js?<?php echo $tag; ?>"></script>
<script src="js/common.js?<?php echo $tag; ?>"></script>
<script src="js/postcard.js?<?php echo $tag; ?>"></script>
</body>
</html>
