<!DOCTYPE html  >
<html manifest="/safari.manifest"><!--   -->
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/css/jquery.mobile-1.3.1.min.css" />
        <link rel="stylesheet" href="/css/kacha.css" />
        <link rel="stylesheet" href="/css/jquery.shadow.css" />
        <script src="/js/jquery-1.9.0.min.js"></script>
        <script src="/js/artDialog.js"></script>
        <script src="/js/jquery.mobile-1.3.1.min.js"></script>
        <script src="/js/google.fastbutton.js"></script>
        <script src="/js/jquery.google.fastbutton.js"></script>
        <script src="/js/jquery.event.move.js"></script>
        <script src="/js/jquery.shadow.js"></script>
        <script src=<?php echo '"/js/kacha.js?' . $tag . '"'; ?> ></script>
    </head>

    <body>
        <div id="content" data-role="content">

            <div data-role='page' id='loadingPage' data-title='泡海明信片' class='page'>
                <div align="center">
                    <p>加载中...</p>
                </div>
            </div>

            <div data-role="page" id="uploadPhotoPage" data-title="制作明信片" class="page">
                <div data-role="content" align="center">
                    <div style="height:530px;">

                        <?php for ($i = 1; $i <= 6; $i += 1) { ?>
                            <img class="thumbnail" src='/images/small/templateVBg.png' style=<?php echo '"top:calc((' . $i . ' - 1)*85px + 15px);"'; ?> ></img>
                            <img class="thumbnail" id=<?php echo 'templateThumbnail' . $i; ?>  data-index=<?php echo $i; ?> src=<?php echo '/images/small/template' . $i . '.png'; ?> style=<?php echo '"top:calc((' . $i . ' - 1)*85px + 15px);"'; ?> ></img>
                        <?php } ?>

                        <img class="postcard" src="/images/small/templateVBg.png"></img>
                        <div class="postcard">
                            <canvas id="userImg" style="position:absolute;"></canvas>
                        </div>
                        <img id="templateImg"   class="postcard"></img>
                        <div id="touchLayer"    class="postcard" style="cursor:move;"></div>
                    </div>
                    <input id="submitPhotoButton" data-theme="e" value="下一步" type="button"></input>
                    <input id="userName" type="hidden" value=<?echo $username ?> ></input>
                    <input id="userPicUrl" type="hidden" value=<?echo $picurl ?> ></input>
                </div>
            </div>

            <div data-role="page" id="messagePage" data-title="留言" class="page">
                <div data-role="content" align="left">
                    <div>想说的话</div>
                    <textarea id="messageinput" rows="3" cols="20" placeholder="留言">思念是一季的花香，漫过山谷，笼罩你我，而祝福是无边的关注，溢出眼睛，直到心底，愿愉快伴你一生。</textarea>
                    <div>你的姓名</div>
                    <input type="text" id="nameinput" placeholder="你的姓名" style="" value="飞鸽"/>
                    <input id="voiceMessageButton" data-theme="e" value="语音留言" type="button"></input>
                    <input id="submitMessageButton" data-theme="e" value="下一步" type="button"></input>
                </div>
            </div>

            <div data-role="page" id="addressPage" data-title="收信地址" class="page">
                <div data-role="content" align="left">
                    <div>收信人地址</div>
                    <input type="text" id="cityinput" placeholder="城市"/>
                    <input type="text" id="streetinput" placeholder="街道门牌"/>
                    <input type="text" id="zipcodeinput" placeholder="邮编"/>
                    <input type="text" id="recipientinput" placeholder="收件人姓名"/>
                    <input type="text" id="mobileinput" placeholder="联系电话"/>

                    <input id="submitAddressButton" data-theme="e" value="下一步" type="button">
                </div>
            </div>

            <div data-role="page" id="previewPage" data-title="预览" class="page">
                <div data-role="content" align="center">
                    <div style="height:370px;">
                        <div class="postcard previewpostcard">
                            <canvas id="previewUserImg" style="position:absolute; left:0"></canvas>
                        </div>
                        <img id="previewTemplateImg"   class="postcard previewpostcard"></img>
                    </div>

                    <div class="previewpostcardback" style="top:370px; width:320px; height:200px;">
                        <img class="postcardback" src="/images/small/postCardBack.png" style="width:320px; height:200px; position:absolute; left:0"></img>

                        <div style="position:absolute; width:320px; height:200px; left:0">
                            <div id="zipcodePreview" style="font-size:17px; letter-spacing:10px; top:17px; left:27px; position:absolute;"></div>
                            <div id="messagePreview" style="font-size:12px; text-align:left; top:50px; left:8px; width:155px; position:absolute;"></div>
                            <div id="senderNamePreview" style="font-size:12px; top:140px; left:100px; position:absolute;"></div>
                            <div id="addressPreview" style="font-size:11px; text-align:left; top:75px; left:160px; width:140px; position:absolute;"></div>
                            <div id="recipientPreview" style="font-size:14px; left:170px; top:135px; position:absolute;"></div>
                        </div>
                    </div>
                    <input id="previewConfirmButton" data-theme="e" value="下一步" type="button">
                </div>
            </div>

            <div data-role='page' id='paymentPage' data-title='支付' class='page'>
                <script src="/js/md5.js"></script>
                <script src="/js/sha1.js"></script>
                <div data-role="content" align="center">
                        <input id="submitPaymentButton1" data-theme="e" value="立即付款 5 元" type="button">
                        <input id="submitPaymentButton2" data-theme="e" value="兴业银行卡支付 1 元" type="button">
                </div>
            </div>

            <div data-role='page' id='payingPage' data-title='支付' class='page'>
                <div data-role="content" align="center">
                    <img id="payImg" src="/images/small/paying.jpg" alt="paying.jpg" width="100%" height="100%" style="padding:0; margin:0; border:0;">
                    <input id="submitPayDoneButton" data-theme="e" value="确 定" type="button">
                </div>
            </div>

            <div data-role="page" id="completePage" data-title="完成" class="page">
                <div data-role="content" align="center">
                    <h3>明信片创建成功，很快将为你邮寄！</h3>

                    <div class="bshare-custom">
                        <a title="分享到QQ空间" class="bshare-qzone"></a>
                        <a title="分享到新浪微博" class="bshare-sinaminiblog"></a>
                        <a title="分享到腾讯微博" class="bshare-qqmb"></a>
                        <!-- <a title="分享到QQ" class="bshare-qqim"></a> -->
                    </div>

                    <script type="text/javascript" charset="utf-8" src="http://static.bshare.cn/b/buttonLite.js#uuid=<你的UUID>&style=-1"></script>
                    <script type="text/javascript" charset="utf-8" src="http://static.bshare.cn/b/bshareC3.js"></script>
                </div>
            </div>

        </div>
    </body>
</html>