<!DOCTYPE html  >
<html manifest="/safari.manifest"><!--  -->
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/css/jquery.mobile-1.3.1.min.css" />
        <link rel="stylesheet" href="/css/kacha.css" />
        <link rel="stylesheet" href="/css/jquery.shadow.css" />
        <script src="/js/jquery-1.9.0.min.js"></script>
        <script src="/js/artDialog.js"></script>
        <script src="/js/jquery.mobile-1.3.1.min.js"></script>
        <script src="/js/google.fastbutton.js"></script>
        <script src="/js/jquery.google.fastbutton.js"></script>
        <script src="/js/jquery.event.move.js"></script>
        <script src="/js/jquery.shadow.js"></script>
        <script src=<?php echo '"/js/util.js?' . $tag . '"'; ?> ></script>
        <script src=<?php echo '"/js/index.js?' . $tag . '"'; ?> ></script>
    </head>

    <body>
        <div id="content" data-role="content">

            <input id="userName" type="hidden" value=<?echo $username ?> ></input>
            <input id="userPicUrl" type="hidden" value=<?echo $picurl ?> ></input>

            <div data-role='page' id='loadingPage' data-title='泡海明信片' class='page'>
                <div align="center">
                    <p>加载中...</p>
                </div>
            </div>

            <div data-role="page" id="uploadPhotoPage" data-title="制作明信片" class="page">
                <div data-role="content" align="center">
                    <div style="height:530px;">

                        <?php for ($i = 1; $i <= 6; $i += 1) { ?>
                            <img class="thumbnail" src='/images/small/templateVBg.png' style=<?php echo '"top:calc((' . $i . ' - 1)*85px + 15px);"'; ?> ></img>
                            <img class="thumbnail" id=<?php echo 'templateThumbnail' . $i; ?>  data-index=<?php echo $i; ?> src=<?php echo '/images/small/template' . $i . '.png'; ?> style=<?php echo '"top:calc((' . $i . ' - 1)*85px + 15px);"'; ?> ></img>
                        <?php } ?>

                        <img class="postcard" src="/images/small/templateVBg.png"></img>
                        <div class="postcard">
                            <canvas id="userImg" style="position:absolute;"></canvas>
                        </div>
                        <img id="templateImg"   class="postcard"></img>
                        <div id="touchLayer"    class="postcard" style="cursor:move;"></div>
                    </div>
                    <input id="submitPhotoButton" data-theme="e" value="下一步" type="button"></input>
                </div>
            </div>
        </div>
    </body>
</html>