<head>
    <title>趣邮明信片</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="content-type" content="text/html;charset=utf-8">
    <link rel="stylesheet" href="/css/bootstrap.min.css" />
    <style type="text/css">
        .table {
            margin-left: 5px;
            margin-top:40px;
        }
        table tr th, table tr td {
            font-size: 12;
        }
        .background {
            top: 0;
            left: 0;
            bottom: 0;
            z-index: -1;
            width: 100%;
            height: 100%;
            position: absolute;
        }
    </style>
</head>
<body>
<table class="table" >
    <tr>
        <th>订单号</th>
        <th>日期</th>
        <th>收信人</th>
        <th>状态</th>
    </tr>
<?php foreach ($orders as $order) : ?>
    <tr>
        <img class="background" src="/images/pop3_bg.png" alt="地址簿背景框"/>
        <td><?php
            if ($order->status == 100) { // only unpay order could click
                echo '<a href="'.$this->url('postcard', array('action'=>'index')).'?orderId='.$order->id.'">'.$order->id.'</a>';
            } else {
                echo $order->id;
            }
            ?></td>
        <td><?php echo substr($order->orderDate, 0, 10);?></td>
        <td><?php echo $this->escapeHtml($order->recipient);?></td>
        <td>
            <?php
            switch ($order->status) {
                case 99:
                    echo $this->escapeHtml("已取消");
                    break;
                case 100:// unpay
                {
                    echo '<a href="'.$this->url('postcard', array('action'=>'index')).'?orderId='.$order->id.'">待付款</a>';
                    break;
                }
                case 101:
                case 102:
                case 103:
                {
                    $today = date("Y-m-d");
                    if (substr($order->orderDate, 0, 10) == $today) {
                        $status = "处理中";
                    } else {
                        $status = "已邮寄";
                    }
                    echo $this->escapeHtml($status);
                    break;
                }
                default:
                    echo $this->escapeHtml("已失效");
                    break;
            }

            ?>
        </td>
    </tr>
<?php endforeach; ?>

    <script language="javascript">
        window.onload = function() {
            if (typeof WeixinJSBridge == "undefined") {
                if ( document.addEventListener ) {
                    document.addEventListener('WeixinJSBridgeReady', onBridgeReady, false);
                } else if (document.attachEvent) {
                    document.attachEvent('WeixinJSBridgeReady', onBridgeReady);
                    document.attachEvent('onWeixinJSBridgeReady', onBridgeReady);
                }
            } else {
                onBridgeReady();
            }
        }

        function onBridgeReady() {
            WeixinJSBridge.call('hideOptionMenu');
        }

    </script>
</body>