<?php
$title = 'Postcard orders';
$this->headTitle($title);
?>

<head>
    <meta http-equiv="content-type" content="text/html;charset=utf-8">

    <script language="javascript">
    function deleteDiv(ele){
     ele.parentNode.parentNode.removeChild(ele.parentNode);
    }
    </script>
</head>

<body>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <table class="table">
    <tr>
        <th>id</th>
        <th>orderDate</th>
        <th>userName</th>
        <th>sender</th>
        <th>address</th>
        <th>recipient</th>
        <th>picUrl</th>
        <th>voiceMediaId</th>
        <th>message</th>
        <th>status</th>
        <th>action</th>
        <!-- <th>&nbsp;</th> -->
    </tr>
    <?php foreach ($orders as $order) : ?>
    <tr>
        <td><?php echo $this->escapeHtml($order->id);?></td>
        <td><?php echo $this->escapeHtml($order->orderDate);?></td>
        <td><?php echo $this->escapeHtml($order->userName);?></td>
        <td><?php echo $this->escapeHtml($order->senderName);?></td>
        <td><?php echo $this->escapeHtml($order->address);?></td>
        <td><?php echo $this->escapeHtml($order->recipient);?></td>
        <td><?php echo $this->escapeHtml($order->picUrl);?></td>
        <td><?php echo $this->escapeHtml($order->voiceMediaId);?></td>
        <td><?php echo $this->escapeHtml($order->message);?></td>
        <td>
            <?php 
            switch ($order->status) {
                case 99:
                    $status = "已取消";
                    break;
                case 100:
                    $status = "待支付";
                    break;
                case 101:
                    $status = "已支付";
                    break;
                case 102:
                    $status = "已打印";
                    break;
                case 103:
                    $status = "已发货";
                    break;
                default:
                    $status = $order->status;
                    break;
            }
            echo $this->escapeHtml($status);
            ?>
        </td>
        <td>
            <?php 
            $status = '';
            switch ($order->status) {
                case 101:
                    $status = "已完成打印";
                    $newStatus = 102;
                    break;
                case 102:
                    $status = "已完成发货";
                    $newStatus = 103;
                    break;
                default:
                    break;
            }

            if ($status != '') {
                echo "<a href=" . $this->url('postcard', array('action'=>'update', 'id' => $order->id, 'status' => $newStatus)).'>'.$status.'</a>';
                // echo "<input type='button' style='background:#fce3b1' value=".$status." onclick=updateStatus()>";
            }
            // echo $this->escapeHtml($status); <div style="border:1px solid #ccc;">
            ?>
        </td>
    </tr>
    <?php endforeach; ?>
    </table>
</body>