<!DOCTYPE html  >
<html manifest="/safari.manifest"><!--    -->
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/css/jquery.mobile-1.3.1.min.css" />
        <link rel="stylesheet" href="/css/kacha.css" />
        <link rel="stylesheet" href="/css/jquery.shadow.css" />
        <script src="/js/jquery-1.9.0.min.js"></script>
        <script src="/js/artDialog.js"></script>
        <script src="/js/jquery.mobile-1.3.1.min.js"></script>
        <script src="/js/google.fastbutton.js"></script>
        <script src="/js/jquery.google.fastbutton.js"></script>
        <script src="/js/jquery.event.move.js"></script>
        <script src="/js/jquery.shadow.js"></script>
        <script src=<?php echo '"/js/util.js?' . $tag . '"'; ?> ></script>`
        <script src=<?php echo '"/js/pay.js?' . $tag . '"'; ?> ></script>
    </head>

    <body>
        <div id="content" data-role="content">

            <input id="orderId" type="hidden" value=<?php echo $orderId ?> ></input>

            <div data-role='page' id='loadingPage' data-title='泡海明信片' class='page'>
                <div align="center">
                    <p>加载中...</p>
                </div>
            </div>

            <div data-role='page' id='paymentPage' data-title='支付' class='page'>
                <script src="/js/md5.js"></script>
                <script src="/js/sha1.js"></script>
                <div data-role="content" align="center">
                        <input id="submitPaymentButton1" data-theme="e" value="立即付款 5 元" type="button">
                        <input id="submitPaymentButton2" data-theme="e" value="兴业银行卡支付 1 元" type="button">
                </div>
            </div>

            <div data-role='page' id='payingPage' data-title='支付' class='page'>
                <div data-role="content" align="center">
                    <img id="payImg" src="/images/small/paying.jpg" alt="paying.jpg" width="100%" height="100%" style="padding:0; margin:0; border:0;">
                    <input id="submitPayDoneButton" data-theme="e" value="确 定" type="button">
                </div>
            </div>

            <div data-role="page" id="completePage" data-title="完成" class="page">
                <div data-role="content" align="center">
                    <h3>明信片创建成功，很快将为你邮寄！</h3>

                    <div class="bshare-custom">
                        <a title="分享到QQ空间" class="bshare-qzone"></a>
                        <a title="分享到新浪微博" class="bshare-sinaminiblog"></a>
                        <a title="分享到腾讯微博" class="bshare-qqmb"></a>
                        <!-- <a title="分享到QQ" class="bshare-qqim"></a> -->
                    </div>

                    <script type="text/javascript" charset="utf-8" src="http://static.bshare.cn/b/buttonLite.js#uuid=<你的UUID>&style=-1"></script>
                    <script type="text/javascript" charset="utf-8" src="http://static.bshare.cn/b/bshareC3.js"></script>
                </div>
            </div>

        </div>
    </body>
</html>