<?php
$title = '趣邮明信片－已付款订单';
$this->headTitle($title);
?>

<head>
    <meta http-equiv="content-type" content="text/html;charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <base target="_blank">
    <script type="text/javascript" src="/client/js/zepto.min.js"></script>
    <script language="javascript">
    function deleteDiv(ele){
     ele.parentNode.parentNode.removeChild(ele.parentNode);
    }
        $(document).ready(function() {
            $("a").on('click', function () {
                $(this).css('color', 'gray');
            });

            $('#activityId').on('keyup', function () {
                var value = $(this).val();
                if (!value) {
                    $("tr[activityId]").show();
                } else {
                    $("tr[activityId]").hide();
                    $("tr[activityId=" + value + "]").show();
                }
            });

            $('#payDate').on('keyup', function () {
                var value = $(this).val();
                if (!value) {
                    $("tr[payDate]").show();
                } else {
                    $("tr[payDate]").hide();
                    $("tr[payDate*=" + value + "]").show();
                }
            });

            $('#orderId').on('keyup', function () {
                var value = $(this).val();
                if (!value) {
                    $("tr[orderId]").show();
                } else {
                    $("tr[orderId]").hide();
                    $("tr[orderId*=" + value + "]").show();
                }
            });
        });
    </script>
</head>

<body>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <table class="table">
    <tr>
        <th>活动id<input type="text" id="activityId" /></th>
        <th>支付日期<input type="text" id="payDate" ></th>
        <th>订单号<input type="text" id="orderId" /></th>
        <th>价格</th>
        <th>收信地址</th>
        <th>收信人</th>
        <th>收信人手机</th>
        <th>实时生成图片</th>
    </tr>
    <?php foreach ($orders as $order) : ?>
    <tr activityId="<?php echo $this->escapeHtml($order->activityId);?>" payDate="<?php echo $this->escapeHtml($order->payDate);?>" orderId="<?php echo $this->escapeHtml($order->id);?>">
        <td><?php echo $this->escapeHtml($order->activityId);?></td>
        <td><?php echo $this->escapeHtml($order->payDate);?></td>
        <td><?php echo $this->escapeHtml($order->id);?></td>
        <td><?php echo $this->escapeHtml($order->price);?></td>
        <td><?php echo $this->escapeHtml($order->address);?></td>
        <td><?php echo $this->escapeHtml($order->recipient);?></td>
        <td><?php echo $this->escapeHtml($order->recipientMobile);?></td>
        <td>
            <?php 
            echo "<a href=" . $this->url('postcard', array('action'=>'getpicture', 'id' => $order->id, 'status' => '0')).'>正面</a>';
            echo "  ｜  ";
            echo "<a href=" . $this->url('postcard', array('action'=>'getpicture', 'id' => $order->id, 'status' => '1')).'>背面</a>';
                // echo "<input type='button' style='background:#fce3b1' value=".$status." onclick=updateStatus()>";
            // echo $this->escapeHtml($status); <div style="border:1px solid #ccc;">
            ?>
        </td>
    </tr>
    <?php endforeach; ?>
    </table>
</body>