<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="/css/common.css?<?php echo $tag; ?>"/>
</head>
<body>
    <div class="page3 pa">
        <div style="font-size:10; color:white; position: absolute; top: 2px; left: 10;">
            看这边“趣邮明信片”<br>
            <div onclick="javascript:WeixinJSBridge.call('closeWindow');">点击你也可以订制属于你的个性明信片哦</div>
        </div>

        <div class="imgLayer_a pa" style="top: 40px;">
            <img style="width: 203px; top: 30px;" src=<?php echo 'http://'.$_SERVER['HTTP_HOST'].'/postcard/shareimage/'. $orderId; ?> >
        </div>
    </div>
    <div style="position: absolute; top: 350px; left: 0%; margin-left: 0px; width: 100%">
        <audio src=<?php echo '"'.$file.'"'?> controls="controls" autoplay name="media" style="width: 100%">
            您的浏览器不支持收听，请用其他手机尝试。
        </audio>
    </div>
</body>
</html>