<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <style type="text/css">
        html, body {
            width: 100%;
        }
        body {
            padding: 0;
            margin: 0;
            background: black;
        }
    </style>
</head>
<body>
    <div style="font-size:10; color:white; position: absolute; top: 10px; left: 10;">
        看这边“趣邮明信片”<br>
        <div onclick="javascript:WeixinJSBridge.call('closeWindow');">点击你也可以订制属于你的个性明信片哦</div>
    </div>

    <div align=center style="position: absolute; top: 40px; width: 100%; height: 280px; padding:0 10px; box-sizing: border-box;">
        <img style="max-width: 100%; max-height:80%;" src=<?php echo 'http://'.$_SERVER['HTTP_HOST'].'/postcard/shareimage/'. $orderId; ?> >
    </div>
    <div style="position: absolute; top: 350px; width: 100%">
        <audio src=<?php echo '"'.$file.'"'?> controls="controls" autoplay name="media" style="width: 100%">
            您的浏览器不支持收听，请用其他手机尝试。
        </audio>
    </div>
</body>
</html>
