<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>step3</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <link rel="stylesheet" href="css/reset.css"/>
    <link rel="stylesheet" href="css/common.css"/>
</head>
<body>
<input id="var-user-name" type="hidden" value="" />
<input id="var-order-id" type="hidden" value="" />
<input id="var-user-picurl" type="hidden" value="images/test_img.jpg" />
<input id="var-offset-x" type="hidden" value= "-0.34074074074074073" />
<input id="var-offset-y" type="hidden" value="0" />
<input id="var-template-index" type="hidden" value="4" />
<input id="var-template-rotate-index" type="hidden" value="2" />
<div class="container">
    <!--菜单条-->
    <div class="menuBar h42">
        <a href="#" class="changeImg">更换图片</a>
        <a href="#" class="next">下一步</a>
    </div>
    <!--面包屑-->
    <div class="breadNav" id="crumbs">
        <ul class="frsb">
            <li><a href="#1">第一步</a></li>
            <li><a href="#2">第二步</a></li>
            <li><a href="#3" class="current">第三步</a></li>
        </ul>
    </div>
    <div class="page3 pa">
        <div class="bigImg_a pa">
            <div class="bgLayer_a pa"><img class="bgLayer_img_a" src="images/big_bg.png"></div>
            <div class="imgLayer_a pa"><img class="imgLayer_img_a" src="images/test_img.jpg"></div>
        </div>
        <div class="frontCover pa">
            <img src="images/front_cover.png" alt="新信封背景"/>
            <div class="postZip"></div>
            <div class="zhufuContent"></div>
            <div class="youchuo_a"></div>
            <div class="address_a"></div>
        </div>
        <input type="image" id="back_modify" class="back_modify getZ pa w150h50" src="images/fanhuixiugai.png" alt="返回修改"/>
        <input type="image" id="pay_conf" class="pay_conf pa w150h50" src="images/querenzhifu.png" alt="确认支付"/>
    </div>
</div>
<script src="js/classie.js"></script>
</body>
</html>