
<script type="text/javascript">
    $(function(){
        var varObj = $("#global-var");
        userName = varObj.data("username");
        window.location.href = "http://"+window.location.host+"/postcard?partnerId=00001&actId=102&username="+userName+"&picurl=https://mmbiz.qlogo.cn/mmbiz/j8WFfyvBAo9PEPFBNPj5K9AW9icXTMb0K7gEb2Nxys2Pqm9PnIpdnFUdbawsEbBWSW00g2yicCAuiaBoG26jLCibAQ/0&nonce=201502161707";
    });
</script>

