<style type="text/css">
    body {
        margin:0;
        padding:0;
    }
</style>
<script type="text/javascript">
    function initPage() {
        var screenWidth = parseInt($("body").css("width"));
        var imageHeight = parseInt($("#background")[0].height);
        var realImageWidth = 600;
        var realImageHeight = 1024;
        var realX1 = 194;
        var realY1 = 459;
        var realX2 = 414;
        var realY2 = 516;

        var x1 = parseInt(screenWidth *  realX1 / realImageWidth);
        var y1 = parseInt(imageHeight * realY1 / realImageHeight);

        var x2 = parseInt(screenWidth *  realX2 / realImageWidth);
        var y2 = parseInt(imageHeight * realY2 / realImageHeight);

        $("#button-area").attr("coords", x1 +"," + y1 + "," + x2 + "," + y2);
    }

    function makePostcard(data) {
        window.location.href = data.url;
    }

    window.onload = initPage;

    $(function() {
        actIntro.init(107, "00001");

        $("#button-area").on("click", function () {
            actIntro.chooseImage(makePostcard);
        });
    });
</script>
